import {supabase} from '@/src/lib/supabase';
export type StaffProfile={user_id:string;display_name:string;email:string;role:'owner_admin'|'cashier_technician';active:boolean};
export async function signInStaff(email:string,password:string){const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;return getStaffProfile();}
export async function registerStaff(email:string,password:string){const {data,error}=await supabase.auth.signUp({email:email.trim(),password});if(error)throw error;return data;}
export async function signOutStaff(){await supabase.auth.signOut();}
export async function getStaffProfile():Promise<StaffProfile|null>{const {data:a}=await supabase.auth.getUser();if(!a.user)return null;const {data,error}=await supabase.from('staff_profiles').select('*').eq('user_id',a.user.id).maybeSingle();if(error)throw error;return data as StaffProfile|null;}
export async function getDashboardSummary(){const {data,error}=await supabase.rpc('staff_dashboard_summary');if(error)throw error;return data as any;}
export async function signedUrl(bucket:string,path?:string|null){if(!path)return null;const {data,error}=await supabase.storage.from(bucket).createSignedUrl(path,3600);if(error)return null;return data.signedUrl;}
export async function lookupMemberByQr(qr:string){const {data,error}=await supabase.rpc('staff_lookup_member_by_qr',{p_qr_value:qr});if(error)throw error;const member:any=data;member.avatarUrl=await signedUrl('member-avatars',member.avatar_path);const [b,p]=await Promise.all([supabase.from('bookings').select('id,booking_code,status,created_at,services(name_id)').eq('member_id',member.user_id).neq('status','cancelled').order('created_at',{ascending:false}).limit(8),supabase.from('payments').select('id,payment_code,status,amount,method,created_at').eq('member_id',member.user_id).in('status',['paid','waiting_verification']).order('created_at',{ascending:false}).limit(8)]);if(b.error)throw b.error;if(p.error)throw p.error;return {member,bookings:b.data??[],payments:p.data??[]};}
export async function createCheckin(x:{qr:string;bookingId?:string|null;paymentId?:string|null;overrideReason?:string|null}){const {data,error}=await supabase.rpc('staff_create_checkin',{p_qr_value:x.qr,p_booking_id:x.bookingId??undefined,p_payment_id:x.paymentId??undefined,p_override_reason:x.overrideReason??undefined});if(error)throw error;return data;}
export async function listWaitingPayments(){const {data,error}=await supabase.from('payments').select('id,payment_code,member_id,booking_id,kind,method,status,amount,proof_path,notes,created_at,member_profiles(full_name,member_code),bookings(booking_code)').eq('status','waiting_verification').order('created_at',{ascending:true});if(error)throw error;return Promise.all((data??[]).map(async(p:any)=>({...p,proofUrl:await signedUrl('payment-proofs',p.proof_path)})));}
export async function verifyPayment(id:string,approved:boolean,notes?:string){const {data,error}=await supabase.rpc('staff_verify_manual_payment',{p_payment_id:id,p_approved:approved,p_notes:notes});if(error)throw error;return data;}
export async function listBookings(){const {data,error}=await supabase.from('bookings').select('id,booking_code,status,quoted_total,vehicle_type,vehicle_category,created_at,member_profiles(full_name,member_code),services(name_id,code),booking_slots(starts_at,ends_at)').order('created_at',{ascending:false}).limit(80);if(error)throw error;return data??[];}
export async function updateBookingStatus(id:string,status:string){const {data,error}=await supabase.rpc('staff_update_booking_status',{p_booking_id:id,p_status:status});if(error)throw error;return data;}
export async function searchMembers(q:string){let query=supabase.from('member_profiles').select('user_id,member_code,username,email,full_name,birth_date,status,avatar_path,activated_at,member_membership_summary(reward_points,qualifying_points_12m,level)').order('created_at',{ascending:false}).limit(40);const s=q.trim().replace(/[%(),]/g,'');if(s)query=query.or(`full_name.ilike.%${s}%,member_code.ilike.%${s}%,username.ilike.%${s}%,email.ilike.%${s}%`);const {data,error}=await query;if(error)throw error;return data??[];}
export async function updateMemberStatus(id:string,status:string,reason?:string){const {data,error}=await supabase.rpc('owner_update_member_status',{p_member_id:id,p_status:status,p_reason:reason});if(error)throw error;return data;}
export async function updateMemberBirthDate(id:string,birthDate:string,reason:string){const {data,error}=await supabase.rpc('owner_update_member_birth_date',{p_member_id:id,p_birth_date:birthDate,p_reason:reason});if(error)throw error;return data;}
export async function adjustMemberPoints(id:string,delta:number,description:string){const {data,error}=await supabase.rpc('owner_adjust_member_points',{p_member_id:id,p_delta:delta,p_description:description});if(error)throw error;return data;}
