import { decode } from 'base64-arraybuffer';
import {supabase} from '@/src/lib/supabase';
export type StaffProfile={user_id:string;display_name:string;email:string;role:'owner_admin'|'cashier_technician';active:boolean};
export async function signInStaff(email:string,password:string){const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;return getStaffProfile();}
export async function registerStaff(email:string,password:string){const {data,error}=await supabase.auth.signUp({email:email.trim(),password});if(error)throw error;return data;}
export async function signOutStaff(){await supabase.auth.signOut();}
export async function getStaffProfile():Promise<StaffProfile|null>{const {data:a}=await supabase.auth.getUser();if(!a.user)return null;const {data,error}=await supabase.from('staff_profiles').select('*').eq('user_id',a.user.id).maybeSingle();if(error)throw error;return data as StaffProfile|null;}
export async function getDashboardSummary(){const {data,error}=await supabase.rpc('staff_dashboard_summary');if(error)throw error;return data as any;}
export async function signedUrl(bucket:string,path?:string|null){if(!path)return null;const {data,error}=await supabase.storage.from(bucket).createSignedUrl(path,3600);if(error)return null;return data.signedUrl;}
export async function lookupMemberByQr(qr:string){const {data,error}=await supabase.rpc('staff_lookup_member_by_qr',{p_qr_value:qr});if(error)throw error;const member:any=data;member.avatarUrl=await signedUrl('member-avatars',member.avatar_path);const [b,p]=await Promise.all([supabase.from('bookings').select('id,booking_code,status,created_at,services(name_id)').eq('member_id',member.user_id).neq('status','cancelled').order('created_at',{ascending:false}).limit(8),supabase.from('payments').select('id,payment_code,status,amount,method,created_at').eq('member_id',member.user_id).in('status',['paid','waiting_verification']).order('created_at',{ascending:false}).limit(8)]);if(b.error)throw b.error;if(p.error)throw p.error;return {member,bookings:b.data??[],payments:p.data??[]};}
export async function createCheckin(x:{qr:string;bookingId?:string|null;paymentId?:string|null;overrideReason?:string|null}){const {data,error}=await supabase.rpc('staff_create_checkin',{p_qr_value:x.qr,p_booking_id:x.bookingId??undefined,p_payment_id:x.paymentId??undefined,p_override_reason:x.overrideReason??undefined});if(error)throw error;return data;}
export async function listWaitingPayments(){const {data,error}=await supabase.from('payments').select('id,payment_code,member_id,booking_id,kind,method,status,amount,proof_path,notes,created_at,member_profiles(full_name,member_code),bookings(booking_code)').eq('status','waiting_verification').order('created_at',{ascending:true});if(error)throw error;return Promise.all((data??[]).map(async(p:any)=>({...p,proofUrl:await signedUrl('payment-proofs',p.proof_path)})));}
export async function verifyPayment(id:string,approved:boolean,notes?:string){const {data,error}=await supabase.rpc('staff_verify_manual_payment',{p_payment_id:id,p_approved:approved,p_notes:notes});if(error)throw error;return data;}
export async function listBookings(){const {data,error}=await supabase.from('bookings').select('id,booking_code,status,quoted_total,vehicle_type,vehicle_category,created_at,member_profiles(full_name,member_code),services(name_id,code),booking_slots(starts_at,ends_at)').order('created_at',{ascending:false}).limit(80);if(error)throw error;return data??[];}
export async function updateBookingStatus(id:string,status:string){const {data,error}=await supabase.rpc('staff_update_booking_status',{p_booking_id:id,p_status:status});if(error)throw error;return data;}
export async function searchMembers(q:string){let query=supabase.from('member_profiles').select('user_id,member_code,username,email,full_name,birth_date,status,avatar_path,activated_at,member_membership_summary(reward_points,qualifying_points_12m,level)').order('created_at',{ascending:false}).limit(40);const s=q.trim().replace(/[%(),]/g,'');if(s)query=query.or(`full_name.ilike.%${s}%,member_code.ilike.%${s}%,username.ilike.%${s}%,email.ilike.%${s}%`);const {data,error}=await query;if(error)throw error;return data??[];}
export async function updateMemberStatus(id:string,status:string,reason?:string){const {data,error}=await supabase.rpc('owner_update_member_status',{p_member_id:id,p_status:status,p_reason:reason});if(error)throw error;return data;}
export async function updateMemberBirthDate(id:string,birthDate:string,reason:string){const {data,error}=await supabase.rpc('owner_update_member_birth_date',{p_member_id:id,p_birth_date:birthDate,p_reason:reason});if(error)throw error;return data;}
export async function adjustMemberPoints(id:string,delta:number,description:string){const {data,error}=await supabase.rpc('owner_adjust_member_points',{p_member_id:id,p_delta:delta,p_description:description});if(error)throw error;return data;}
export async function listBanners(){const {data,error}=await supabase.from('banners').select('*').order('sort_order').order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function uploadBanner(input:{base64:string;mimeType?:string|null}){const {data:a}=await supabase.auth.getUser();if(!a.user)throw new Error('AUTH_REQUIRED');const ext=input.mimeType==='image/png'?'png':input.mimeType==='image/webp'?'webp':'jpg';const path=`${a.user.id}/${Date.now()}.${ext}`;const {error}=await supabase.storage.from('banners').upload(path,decode(input.base64),{contentType:input.mimeType??'image/jpeg'});if(error)throw error;return path;}
export async function saveBanner(input:any){const {data,error}=await supabase.rpc('owner_save_banner',{p_banner_id:input.id??undefined,p_title:input.title,p_image_path:input.image_path,p_action_type:input.action_type??'none',p_action_value:input.action_value??undefined,p_sort_order:Number(input.sort_order??0),p_active:Boolean(input.active),p_starts_at:input.starts_at||undefined,p_ends_at:input.ends_at||undefined});if(error)throw error;return data;}
export async function listStoryReports(){const {data:reports,error}=await supabase.from('story_reports').select('*').eq('status','open').order('created_at',{ascending:true});if(error)throw error;const ids=(reports??[]).map((x:any)=>x.story_id);if(!ids.length)return[];const {data:stories,error:se}=await supabase.from('stories').select('id,member_id,caption,media_path,status,created_at').in('id',ids);if(se)throw se;const mids=Array.from(new Set((stories??[]).map((x:any)=>x.member_id)));const {data:members,error:me}=await supabase.from('member_profiles').select('user_id,full_name,member_code').in('user_id',mids);if(me)throw me;const sm=new Map((stories??[]).map((x:any)=>[x.id,x]));const mm=new Map((members??[]).map((x:any)=>[x.user_id,x]));return Promise.all((reports??[]).map(async(r:any)=>{const story:any=sm.get(r.story_id);return {...r,story,member:story?mm.get(story.member_id):null,mediaUrl:story?await signedUrl('story-media',story.media_path):null};}));}
export async function moderateStory(id:string,action:'moderate'|'delete'|'restore',reason:string,suspend=false){const {data,error}=await supabase.rpc('owner_moderate_story',{p_story_id:id,p_action:action,p_reason:reason,p_suspend_member:suspend});if(error)throw error;return data;}
export async function reviewStoryReport(id:string,status:'reviewed'|'dismissed'|'actioned'){const {data,error}=await supabase.rpc('owner_review_story_report',{p_report_id:id,p_status:status});if(error)throw error;return data;}
export async function listServices(){const {data,error}=await supabase.from('services').select('*,service_prices(*)').order('sort_order');if(error)throw error;return data??[];}
export async function saveServiceConfig(s:any){const {data,error}=await supabase.rpc('owner_update_service_config',{p_service_id:s.id,p_active:s.active,p_booking_enabled:s.booking_enabled,p_capacity_default:Number(s.capacity_default),p_duration_minutes:s.duration_minutes?Number(s.duration_minutes):null,p_requires_deposit:s.requires_deposit,p_minimum_deposit:Number(s.minimum_deposit??0)});if(error)throw error;return data;}
export async function saveServicePrice(serviceId:string,category:string,amount:number){const {data,error}=await supabase.rpc('owner_update_service_price',{p_service_id:serviceId,p_vehicle_category:category,p_amount:amount,p_price_label:undefined,p_active:true});if(error)throw error;return data;}
export async function listSlots(){const {data,error}=await supabase.from('booking_slots').select('*,services(name_id,code)').gte('starts_at',new Date(Date.now()-86400000).toISOString()).order('starts_at').limit(100);if(error)throw error;return data??[];}
export async function saveSlot(input:any){const {data,error}=await supabase.rpc('owner_save_booking_slot',{p_slot_id:input.id??undefined,p_service_id:input.service_id,p_starts_at:input.starts_at,p_capacity:Number(input.capacity),p_priority_only:Boolean(input.priority_only),p_public_release_at:input.public_release_at||undefined,p_status:input.status??'open',p_notes:input.notes??undefined});if(error)throw error;return data;}
export async function listWarranties(){const {data,error}=await supabase.from('coating_warranties').select('*,member_profiles(full_name,member_code),bookings(booking_code)').order('starts_on',{ascending:false}).limit(80);if(error)throw error;return data??[];}
export async function updateWarranty(id:string,status:string,nextMaintenance:string|null,notes?:string){const {data,error}=await supabase.rpc('owner_update_warranty',{p_warranty_id:id,p_status:status,p_next_maintenance_on:nextMaintenance??undefined,p_notes:notes??undefined});if(error)throw error;return data;}
export async function listAuditLogs(){const {data,error}=await supabase.from('audit_logs').select('id,actor_label,action,entity_type,entity_id,created_at,metadata').order('created_at',{ascending:false}).limit(150);if(error)throw error;return data??[];}
